### ISSUE TITLE
Consider adding non Open Source tools

### ISSUE THREAD

**Issue by theodorosploumis** [drupaltools/drupaltools.github.io#9]
Some popular tools like MAMP, WAMP, XAMPP, Acquia Dev Desktop etc are not open source but they are widely used.

Should we add such tools or only open source tools?

I am waiting for your opinions and likes/dislikes.

Thanks!

**Comment by dapseen** [comment]
*Project drupaltools.github.io, a list of open-source tools used for Drupal development and other Drupal related tasks*


We should not deviate from the initial vision of the project..
